[phases.setup]
nixPkgs = ["nodejs-18_x", "yarn", "postgresql"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = [
    "npx prisma generate",
    "yarn build"
]

[start]
cmd = "npx prisma migrate deploy && yarn start"
